name: 'node-versioner'
description: 'GitHub Action to version a Node.js project and publish it to GitHub/NPM registry/VS Code Marketplace'
author: 'tjohnsonBCM'
inputs:
  changelog-header:
    description: 'Changelog header used to track changes for new version'
    required: false
    default: ''
  config-file:
    description: 'Path to YAML config'
    required: false
    default: './.github/node-versioner-config.yml'
  github-artifacts:
    description: 'Line-separated list of files to publish in GitHub release'
    required: false
    default: ''
  npm-registry:
    description: 'Registry where NPM package will be published'
    required: false
    default: ''
  npm-token:
    description: 'Token with publish access to NPM registry'
    required: false
    default: ''
  prepublish-cmd:
    description: 'Shell command that will run before project is published'
    required: false
    default: ''
  project-type:
    description: 'Project type for a monorepo (lerna, yarn-workspaces)'
    required: false
    default: ''
  repo-token:
    description: 'Token with push access to GitHub repo'
    required: true
    default: ''
  root-dir:
    description: 'Root directory of Node.js project that contains package.json'
    required: false
    default: ''
  semver-labels:
    description: 'Comma-separated list of semver labels to detect on PRs'
    required: false
    default: 'release-major,release-minor,release-patch'
  version-strategy:
    description: 'Strategy for updating package version (none, compare, labels)'
    required: false
    default: 'labels'
  vsce-token:
    description: 'Token with publish access to VS Code Marketplace'
    required: false
    default: ''
outputs:
  new-version:
    description: 'The new package version if it has changed'
runs:
  using: 'node12'
  main: 'dist/index.js'
